name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
      - master
      - develop
    paths:
      - 'docs/**'
      - 'scripts/**'
      - '__version__.py'
      - 'main.py'
      - 'config.py'
      - 'requirements.txt'
      - '.github/workflows/deploy-docs.yml'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Build documentation with Sphinx
        run: |
          cd docs/sphinx && make clean html
        continue-on-error: false

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/sphinx/_build/html
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: ./docs_build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs_build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Success notification
        run: |
          echo "✅ Documentation deployed successfully!"
          echo "📚 Available at: ${{ steps.deployment.outputs.page_url }}"
